### ISSUE TITLE
Generator re-pads shuffled instances which are already padded

### ISSUE THREAD

**Issue by DeNeutoy** [allenai/deep_qa#360]
![screen shot 2017-05-16 at 11 00 04 am](https://cloud.githubusercontent.com/assets/16001974/26120999/9a5e733a-3a27-11e7-929d-a65aef24554c.png)

Training using the data generator results in a slow down due to incremental padding from the noise introduced during shuffling.

**Comment by matt-gardner** [comment]
The easiest fix is just to copy the dataset [here](https://github.com/allenai/deep_qa/blob/6a0039822f9f2c727151b6143e2214d331bdc111/deep_qa/data/data_generator.py#L116), before creating batches.  Doing it in a way that avoids this copying would be really intrusive to the instance code, because you'd have to keep track of (or figure out after the fact) what part of the instance is just padding, and what isn't.  I don't think the additional copy should be a big deal.

I'll get to this soon, if you don't get to it first.  My day's pretty busy today, but I should have time tomorrow.  It should just be a one-line fix, though having a test to be sure it's doing the right thing would also be good.

**Comment by DeNeutoy** [comment]
#361
